namespace UniversityWebsite.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class MakeServiceIdAutoGenerated : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Volunteers", "Service_Id", "dbo.Services");
            DropPrimaryKey("dbo.Services");
            AlterColumn("dbo.Services", "Service_Id", c => c.Int(nullable: false, identity: true));
            AddPrimaryKey("dbo.Services", "Service_Id");
            AddForeignKey("dbo.Volunteers", "Service_Id", "dbo.Services", "Service_Id", cascadeDelete: true);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Volunteers", "Service_Id", "dbo.Services");
            DropPrimaryKey("dbo.Services");
            AlterColumn("dbo.Services", "Service_Id", c => c.Int(nullable: false));
            AddPrimaryKey("dbo.Services", "Service_Id");
            AddForeignKey("dbo.Volunteers", "Service_Id", "dbo.Services", "Service_Id", cascadeDelete: true);
        }
    }
}
